import type { Metadata } from "next";
import { PackageCreateForm } from "@/components/tenant/package-create-form";
import { TenantModel } from "@/db/models/tenant.model";
import { requirePageRole } from "@/server/middleware/page-auth";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Create Package" };

export default async function NewPackagePage() {
  const auth = await requirePageRole("TENANT_ADMIN");
  const tenant = auth.user.tenantId
    ? await TenantModel.findById(auth.user.tenantId).lean()
    : null;
  return (
    <div className="max-w-3xl">
      <p className="mb-2 font-mono text-[10px] tracking-[0.3em] text-signal uppercase">
        Operations — create package
      </p>
      <h1 className="text-3xl font-bold tracking-[-0.02em] text-paper">Register a shipment.</h1>
      <p className="mt-2 mb-8 text-sm leading-6 text-fog">
        The tracking ID is generated by the server on submit — you never
        type one. Creation is atomic: the package and its initial
        &quot;Pending&quot; status event arrive together, or not at all.
      </p>
      <PackageCreateForm companyName={tenant?.companyName ?? "Your company"} slug={tenant?.slug ?? ""} />
    </div>
  );
}
